language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-graphic-template' ]; then cd .. && eval "mv $currentfolder generator-graphic-template" && cd generator-graphic-template; fi
